apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nodejs
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: azkadevops/nodejs:latest 
        name: nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        envFrom:
        - configMapRef:
            name: nodejs-env